version: "3.9"
services:
  web:
    build: ./xmol
    expose:
      - 8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    ports:
      - 443:443
      - 80:80
    depends_on:
      - web
